// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options.proto

package org.eclipse.ecf.grpc.osgigenerator;

public final class OsgiServiceOptionsProto {
  private OsgiServiceOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.eclipse.ecf.grpc.osgigenerator.OsgiServiceOptionsProto.interfaceTypes);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int INTERFACE_TYPES_FIELD_NUMBER = 88888;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      org.eclipse.ecf.grpc.osgigenerator.MethodTypes> interfaceTypes = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.eclipse.ecf.grpc.osgigenerator.MethodTypes.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\roptions.proto\032 google/protobuf/descrip" +
      "tor.proto*,\n\013MethodTypes\022\r\n\tREACTIVEX\020\000\022" +
      "\016\n\nGRPC_UNARY\020\001:H\n\017interface_types\022\037.goo" +
      "gle.protobuf.ServiceOptions\030\270\266\005 \001(\0162\014.Me" +
      "thodTypesB?\n\"org.eclipse.ecf.grpc.osgige" +
      "neratorB\027OsgiServiceOptionsProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    interfaceTypes.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
